config/routes.rb
Rails.application.routes.draw do

  resources :users,  only: [:new, :create, :show, :edit, :update] do
    member do
      get :dashboard
      get :avatar
    end
  end

  resources :welcome
  root to: 'welcome#index'
  get 'auth/twitter/callback', to: 'sessions#create', as: 'signin'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  get 'dashboard', to: 'users#dashboard', as: 'dashboard'

  resources :events
  resources :locations
  resources :user_events

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :user_events
  has_many :users, through: :user_events
  
  belongs_to :location
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :events
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :user_events
  has_many :events, through: :user_events

  def self.from_omniauth(auth)
    if !User.find_by(twitter_id: auth['uid'])
      create_from_omniauth(auth)
    else
      User.find_by(twitter_id: auth['uid'])
    end
  end

  def self.create_from_omniauth(auth)
    create! do |user|
      user.provider         = auth["provider"]
      user.twitter_id       = auth["uid"]
      user.name             = auth["info"]["nickname"]
      user.image            = auth["info"]["image"]
    end
  end

  private

  def user_params
    params.require(:users).permit(:provider, :uid, :nickname, :image)
  end
end

app/models/user_event.rb
class UserEvent < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    # @events = Event.all
  end

  def show

  end

  def new
    # @event = Event.new
  end

  def edit
  end


  def create
     UserNotifier.send_signup_email(@user).deliver
  end

  def update
  end

  def destroy
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    @locations = Location.all
  end

  def show
    @location = Location.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to dashboard_user, notice: "Signed in!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Signed out!"
  end

  def dashboard_user
    return render "errors/404" unless current_user
    @user = current_user
  end
end

app/controllers/user_events_controller.rb
class UserEventsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
  end

  def update
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :dashboard, :destroy]
  helper_method :high_res_profile

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def avatar
    @user = current_user
  end

  def dashboard
    @user = current_user
  end

  def high_res_profile
    current_user.image.sub "_normal", ""
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :provider, :uid, :name)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/user_events_helper.rb
module UserEventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/create.html.erb
<h1>Event#create</h1>
<p>Find me in app/views/event/create.html.erb</p>

app/views/events/destroy.html.erb
<h1>Event#destroy</h1>
<p>Find me in app/views/event/destroy.html.erb</p>

app/views/events/index.html.erb
<h1>Event#index</h1>
<p>Find me in app/views/event/index.html.erb</p>

app/views/events/show.html.erb
<h1>Event#show</h1>
<p>Find me in app/views/event/show.html.erb</p>

app/views/events/update.html.erb
<h1>Event#update</h1>
<p>Find me in app/views/event/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>B-Ball Games</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <%= csrf_meta_tags %>
</head>
<body>
 <%= yield %>
</body>
</html>

app/views/locations/index.html.erb
<h3>
  <% @locations.each do |location| %>
    <%= location.name %>
  <% end %>
</h3>

app/views/locations/show.html.erb
<h1>
<%= @location.name %>
</h1>

app/views/user_events/create.html.erb
<h1>UserEvents#create</h1>
<p>Find me in app/views/user_events/create.html.erb</p>

app/views/user_events/destroy.html.erb
<h1>UserEvents#destroy</h1>
<p>Find me in app/views/user_events/destroy.html.erb</p>

app/views/user_events/edit.html.erb
<h1>UserEvents#edit</h1>
<p>Find me in app/views/user_events/edit.html.erb</p>

app/views/user_events/index.html.erb
<h1>UserEvents#index</h1>
<p>Find me in app/views/user_events/index.html.erb</p>

app/views/user_events/new.html.erb
<h1>UserEvents#new</h1>
<p>Find me in app/views/user_events/new.html.erb</p>

app/views/user_events/show.html.erb
<h1>UserEvents#show</h1>
<p>Find me in app/views/user_events/show.html.erb</p>

app/views/user_events/update.html.erb
<h1>UserEvents#update</h1>
<p>Find me in app/views/user_events/update.html.erb</p>

app/views/user_notifier/send_signup_email.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <h1>Thanks for signing up, <%= @user.name %>!</h1>
    <p>Thanks for joining and have a great day! Now sign in and do
awesome things!</p>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', user_path %>

app/views/users/show.html.erb
<div id="header">
  <h1 class="text-center"><%= current_user.name %></h1>
</div>

<div id="aside">
  <br />
  <div class="twitter-avatar">
    <%= image_tag high_res_profile %>
  </div>
  <div>
    <%= current_user.first_name %>
  </div><br />
  <div>
    <% current_user.events.each do |event| %>
      <strong>Event:</strong>
        <%= event.description %><br /><br />
      <strong>Location: </strong>
        <%= event.location.name.capitalize %>
    <% end %>
  </div><br />
  <div>
    <%= link_to "Edit My Info", edit_user_path(@user) %><br /><br />
    <%= link_to "Sign Out", signout_path %>
  </div>
</div>

<div id="section">
  <div class="future game">
    <h2 id="schedule-game">
      <%= link_to 'Schedule a B-ball game', locations_path %>
        <% Location.all.each do |location| %>
      <% end %>
    </h2>
  </div>
  <h2 id="view-games">View scheduled games</h2><br />
</div>

app/views/welcome/index.html.erb
<div class="background_image">
</div>


<div class="site-wrapper">
  <div class="site-wrapper-inner">
    <div class="cover-container">
      <div class="inner cover">
        <h1 class="cover-heading">B-Ball Games</h1>
        <p class="lead">Hoop it up with your friends! </p>
        <p class="lead">
          <a href="/auth/twitter" class="btn btn-lg btn-default">
            Sign in with Twitter
          </a>
        </p>
      </div>
    </div>
  </div>
</div>